name: MuleSoft CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version
  EXCHANGE_REPO_URL: https://maven.anypoint.mulesoft.com/api/v3/maven

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
        cache: 'maven'
    
    - name: Validate settings.xml
      run: |
        echo "Validating Maven settings..."
        if [ ! -f .maven/settings.xml ]; then
          echo "Error: settings.xml not found in .maven directory"
          exit 1
        fi
        
    - name: Build and deploy to Exchange
      run: |
        echo "Building Mule application..."
        mvn $MAVEN_CLI_OPTS clean package \
          -s .maven/settings.xml \
          -DskipTests
        
        echo "Deploying to Exchange..."
        ARTIFACT_PATH=$(ls target/*.jar | head -1)
        mvn $MAVEN_CLI_OPTS deploy \
          -s .maven/settings.xml \
          -Dmule.artifact=$ARTIFACT_PATH \
          -Dexchange.repository=anypoint-exchange-v3 \
          -Dexchange.serverId=anypoint-exchange-v3
        
    - name: Deploy to CloudHub
      run: |
        echo "Deploying to CloudHub Sandbox..."
        mvn $MAVEN_CLI_OPTS mule:deploy \
          -s .maven/settings.xml \
          -DmuleDeploy \
          -DskipTests \
          -DskipDeploymentVerification="true" \
          -Ddeployment.environment="sandbox"
    
    - name: Upload artifact for reference
      uses: actions/upload-artifact@v4
      with:
        name: mule-application
        path: target/*.jar