name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Changed to ubuntu-latest (recommended for MuleSoft)

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 11  # Changed to JDK 11 (required for Mule 4)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"  # Changed to temurin (recommended)
          java-version: 11

      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn mule:deploy --settings .maven/settings.xml -DskipMunitTests \
            -Ddeployment.target=CH2 \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" 